name: Deploy Bolt to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup pnpm
      uses: pnpm/action-setup@v3
      with:
        version: 9.7.1

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20.15.1
        cache: 'pnpm'

    - name: Install dependencies
      run: pnpm install

    - name: Build the app
      run: pnpm run build

    - name: Deploy to EC2
      env:
        SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
        HOST: ${{ secrets.EC2_HOST }}
        USER: ${{ secrets.EC2_USER }}
        ENVLOCAL: ${{ secrets.ENVLOCAL }}
      run: |
        echo "$SSH_PRIVATE_KEY" > key.pem
        chmod 600 key.pem
        mkdir -p ~/.ssh
        ssh-keyscan -H $HOST >> ~/.ssh/known_hosts

        ssh -i key.pem -t $USER@$HOST <<EOF
        mkdir -p /home/ubuntu/bolt-building
        EOF

        # scp -i key.pem -r ./* $USER@$HOST:/home/ubuntu/bolt-building/
        rsync -avz --delete -e "ssh -i key.pem" ./ $USER@$HOST:/home/ubuntu/bolt-building/

        ssh -i key.pem -t $USER@$HOST <<EOF
        echo "$ENVLOCAL" > .env.local
        EOF

        ssh -i key.pem -t $USER@$HOST <<EOF
        export PATH=\$PATH:/home/ubuntu/.nvm/versions/node/v20.15.1/bin
        pm2 stop bolt-app || true
        rm -Rf /home/ubuntu/bolt
        mv /home/ubuntu/bolt-building /home/ubuntu/bolt
        pm2 restart bolt-app
        sudo systemctl restart nginx
        EOF
